### 댓글 생성
POST {{apiUrl}}/comments
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "voteId": 1,
  "content": "교촌이 제일 맛있어요~"
}

### 댓글 수정
PATCH {{apiUrl}}/comments/1
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "content": "노통이 제일 맛있어요~"
}

### 댓글 상세조회
GET {{apiUrl}}/comments/1
Authorization: {{authorizationToken}}