### 유저 정보 조회
GET {{apiUrl}}/mypage/users/2/info
Authorization: {{authorizationToken}}

### 유저 정보 수정
PATCH {{apiUrl}}/mypage/users/2/info?gender=F
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8



### 유저 탈퇴
PATCH {{apiUrl}}/mypage/users/2
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

### 비밀번호 변경
PATCH {{apiUrl}}/mypage/users/2/pw
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "curPassword": "1234",
  "newPassword": "4321"
}

### 작성한 투표 목록 조회
GET {{apiUrl}}/mypage/users/2/votes?status=false&lastVoteId=0
Authorization: {{authorizationToken}}

### 참여한 투표 목록 조회
GET {{apiUrl}}/mypage/users/2/ballots?status=false
Authorization: {{authorizationToken}}

### 예측률 조회
GET {{apiUrl}}/mypage/users/2/rate
Authorization: {{authorizationToken}}

### 로그아웃
GET {{apiUrl}}/mypage/users/2/logout
Authorization: {{authorizationToken}}